# Generated by Django 5.0.3 on 2024-08-03 20:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='db_create_activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img_activity', models.ImageField(blank=True, null=True, upload_to='media/activity/')),
                ('activity_name', models.CharField(max_length=30)),
                ('activity_type', models.CharField(choices=[('1 ด้านวิชาการที่ส่งเสริมคุณลักษณะบัณฑิตที่พึงประสงค์', '1 ด้านวิชาการที่ส่งเสริมคุณลักษณะบัณฑิตที่พึงประสงค์'), ('2 ด้านกีฬาหรือการส่งเสริมสุขภาพ', '2 ด้านกีฬาหรือการส่งเสริมสุขภาพ'), ('3 ด้านบำเพ็ญประโยชน์หรือรักษาสิ่งแวดล้อม', '3 ด้านบำเพ็ญประโยชน์หรือรักษาสิ่งแวดล้อม'), ('4 ด้านเสริมสร้างคุณธรรมและจริยธรรม', '4 ด้านเสริมสร้างคุณธรรมและจริยธรรม'), ('5 ด้านส่งเสริมศิลปะและวัฒนธรรม', '5 ด้านส่งเสริมศิลปะและวัฒนธรรม'), ('6 ด้านกิจกรรมอื่นๆ', '6 ด้านกิจกรรมอื่นๆ')], max_length=100)),
                ('start_date_create_activity', models.DateTimeField()),
                ('due_date_create_activity', models.DateTimeField()),
                ('target_number', models.IntegerField(default=0)),
                ('place', models.CharField(max_length=30)),
                ('start_date_activity', models.DateTimeField()),
                ('due_date_activity', models.DateTimeField()),
                ('person_responsible_project', models.CharField(max_length=30)),
                ('project_consultant', models.CharField(max_length=30)),
                ('description', models.CharField(max_length=30)),
                ('credit', models.IntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='create_activity2', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='db_activity_adduser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='db_activity_adduser2', to=settings.AUTH_USER_MODEL)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='db_activity_adduser2', to='Person_responsible_for_the_project.db_create_activity')),
            ],
        ),
    ]
