# Generated by Django 5.0.3 on 2024-08-18 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0002_remove_user_is_recruitment_announcer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='faculty',
        ),
        migrations.AddField(
            model_name='userstudent',
            name='number_of_credits_available',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userstudent',
            name='number_of_credits_required',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
    ]
