# Generated by Django 5.0.3 on 2024-08-18 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0003_remove_user_faculty_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userstudent',
            name='number_of_credits_required',
            field=models.IntegerField(),
        ),
    ]
