# Generated by Django 5.0.3 on 2024-08-18 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0004_alter_userstudent_number_of_credits_required'),
    ]

    operations = [
        migrations.AddField(
            model_name='userstudent',
            name='type_Scholarship_or_Student_loan_fund',
            field=models.CharField(choices=[('ทุน', 'ทุน'), ('กยศ', 'กยศ')], default='', max_length=50),
        ),
    ]
