# Generated by Django 5.0.3 on 2024-08-18 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0005_userstudent_type_scholarship_or_student_loan_fund'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userstudent',
            name='type_Scholarship_or_Student_loan_fund',
            field=models.CharField(choices=[('ทุน', 'ทุน'), ('กยศ', 'กยศ'), ('ทุน, กยศ', 'ทุน, กยศ')], default='', max_length=50),
        ),
    ]
