# Generated by Django 5.0.3 on 2024-08-21 04:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0008_user_number_of_credits_available_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='number_of_credits_available',
        ),
        migrations.RemoveField(
            model_name='user',
            name='number_of_credits_required',
        ),
        migrations.RemoveField(
            model_name='user',
            name='type_Scholarship_or_Student_loan_fund',
        ),
    ]
